# You can edit this messages and set your customs messages :)
# If you enjoy my plugin, please rate 5 stars at SpigotMC.org ;)
# Please report all issues at GitHub.com
# EDIT ONLY 1.7.1 and 1.7.6 IF YOU SUPPORT THIS VERSIONS !! (1.7-1.12)
v1_7_1: "&6[ViaCheck] &rYou are connected from the server with a &b1.7&r's version"
v1_7_6: "&6[ViaCheck] &rYou are connected from the server with a &b1.7&r's version"
v1_8: "&6[ViaCheck] &rYou are connected from the server with a &b1.8&r's version"
v1_9_0: "&6[ViaCheck] &rYou are connected from the server with a &b1.9&r's version"
v1_9_1: "&6[ViaCheck] &rYou are connected from the server with a &b1.9&r's version"
v1_9_2: "&6[ViaCheck] &rYou are connected from the server with a &b1.9&r's version"
v1_9_3: "&6[ViaCheck] &rYou are connected from the server with a &b1.9&r's version"
v1_10: "&6[ViaCheck] &rYou are connected from the server with a &b1.10&r's version"
v1_11: "&6[ViaCheck] &rYou are connected from the server with a &b1.11&r's version"
v1_11_1: "&6[ViaCheck] &rYou are connected from the server with a &b1.11&r's version"
v1_12: "&6[ViaCheck] &rYou are connected from the server with a &b1.12&r's version"
v1_12_1: "&6[ViaCheck] &rYou are connected from the server with a &b1.12&r's version"
v1_12_2: "&6[ViaCheck] &rYou are connected from the server with a &b1.12&r's version"
unknown_version: "&6[ViaCheck] &cERROR! We don't find your minecraft's version.Please report this bug !"