# You can change the plugin's messages in this config.
# EDIT ONLY 1.7.1 and 1.7.6 IF YOU SUPPORT THIS VERSIONS !! (1.7-1.13)
message: "&6[ViaCheck] &fYou joined the server using &b%version%.
unknown_version: "&6[ViaCheck] &cERROR! &rYou are using an unknown version of Minecraft. Please report this bug!"
