# You can change the plugin's messages in this config.
# EDIT ONLY 1.7.1 and 1.7.6 IF YOU SUPPORT THIS VERSIONS !! (1.7-1.15)
v1_7_1: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.7"
v1_7_6: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.7"
v1_8: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.8"
v1_9_0: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.9"
v1_9_1: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.9"
v1_9_2: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.9"
v1_9_3: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.9"
v1_10: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.10"
v1_11: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.11"
v1_11_1: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.11"
v1_12: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.12"
v1_12_1: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.12"
v1_12_2: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.12"
v1_13: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.13"
v1_13_1: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.13.1"
v1_13_2: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.13.2"
v1_14: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.14"
v1_14_1: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.14.1"
v1_14_2: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.14.2"
v1_14_3: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.14.3"
v1_14_4: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.14.4"
v1_15: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.15"
v1_15_1: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.15.1"
v1_15_2: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.15.2"
v1_16: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.16"
v1_16_1: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.16.1".
v1_16_2: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.16.2"
v1_16_3: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.16.3"
v1_16_4: "&6[ViaCheck] &rYou are connected to the server with version &b&o1.16.4"
unknown_version: "&6[ViaCheck] &cERROR! &rYou are using an unknown version of Minecraft. Please report this bug!"
